// DO NOT MODIFY THIS FILE.
// This entire file was automatically generated by ModAssemblyInfo.csproj.
// Make any needed changes in ModAssemblyInfo.csproj.

namespace ChangeCompany
{
    /// <summary>
    /// Make assembly info available as constant strings.
    /// </summary>
    public class ModAssemblyInfo
    {
        public const string Name        = "ChangeCompany";
        public const string Version     = "2.0.1";
        public const string Title       = "Change Company";
        public const string Description = "Change the company for a commercial, industrial, or office building.";
    }
}
