// DO NOT MODIFY THIS FILE.
// This entire file was automatically generated by ModAssemblyInfo.csproj.
// Make any needed changes in ModAssemblyInfo.csproj.

namespace ChangeCompany
{
    /// <summary>
    /// Make assembly info available as constant strings.
    /// </summary>
    public class ModAssemblyInfo
    {
        public const string Name        = "ChangeCompany";
        public const string Version     = "4.0.0";
        public const string Title       = "Change Company";
        public const string Description = "Mod with 4 main features: Change Company, Production Balance, Lock Company, and Company Workplaces.";
    }
}
